version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: 868298891538
    AWS_DEFAULT_REGION: ap-northeast-1
    IMAGE_REPOSITORY_NAME: "868298891538.dkr.ecr.ap-northeast-1.amazonaws.com/internship-app"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker-compose up -d
  build:
    commands:
      - ./gradlew build
      - docker build -t $IMAGE_REPOSITORY_NAME:$IMAGE_TAG .
      - docker push $IMAGE_REPOSITORY_NAME:$IMAGE_TAG
      - printf '[{"name":"internship-app", "imageUri":"%s"}]' $IMAGE_REPOSITORY_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
