spring:
  datasource:
    url: jdbc:mysql://review-db.internship:3306/internship
    username: user
    password: password

  flyway:
    enabled: true
    locations: classpath:/db/migration,classpath:/db/test